window.nutriCalc = window.nutriCalc || {};

nutriCalc.constants = {
  // Activités
  SOMMEIL: 'sommeil',
  REPOS: 'repos',
  ASSIS_CALME: 'assisCalme',
  ASSIS_ACTIF: 'assisActif',
  DEBOUT_CALME: 'deboutCalme',
  MENAGE_LEGER: 'menageLeger',
  PROMENADE: 'promenade',
  MENAGE_SOUTENU: 'menageSoutenu',
  MARCHE_ALERTE: 'marcheAlerte',
  SPORT: 'sport',
  SPORT_SOUTENU: 'sportSoutenu',
  SPORT_INTENSE: 'sportIntense',

  ACTIVITES: [
    'sommeil',
    'repos',
    'assisCalme',
    'assisActif',
    'deboutCalme',
    'menageLeger',
    'promenade',
    'menageSoutenu',
    'marcheAlerte',
    'sport',
    'sportSoutenu',
    'sportIntense',
  ],

  // Source : https://pacompendium.com/
  COEFFICIENTS_ACTIVITES: {
    sommeil: 1.0, // Sommeil, sieste
    repos: 1.3, // Lecture, télévision, tricot, couture calme, passager assis
    assisCalme: 1.5, // Repas calme, conversations, travail de bureau léger
    assisActif: 1.8, // Conduite, travail de bureau actif
    deboutCalme: 2.2, // Toilette, habillage, cuisine simple, petit rangement, vente au comptoir
    menageLeger: 2.5, // Ménage léger, s’occuper d’un enfant, faire quelques courses à pied
    promenade: 2.9, // Marche ~4 km/h : promenade tranquille, balade du chien, flânerie
    menageSoutenu: 3.5, // Ménage soutenu, petit jardinage, déplacements à bon pas
    marcheAlerte: 4.5, // Marche 6 km/h
    sport: 6.0, // Vélo loisir 16–19 km/h, natation tranquille, sport collectif loisir
    sportSoutenu: 8.5, // Jogging 8–9 km/h, vélo 20–22 km/h, natation soutenue, sport de raquette vif
    sportIntense: 10.0, // Course >10 km/h, cyclisme >23 km/h, natation rapide
  },

  LABELS_ACTIVITES_ADULTES: {
    sommeil: 'Sommeil, sieste',
    repos: 'Repos (lecture, TV)',
    assisCalme: 'Activité assise calme',
    assisActif: 'Travail de bureau actif',
    deboutCalme: 'Activité debout calme',
    menageLeger: 'Ménage léger',
    promenade: 'Promenade',
    menageSoutenu: 'Ménage soutenu',
    marcheAlerte: 'Marche alerte',
    sport: 'Sport loisir',
    sportSoutenu: 'Sport soutenu',
    sportIntense: 'Sport intense',
  },

  NUTRIMENTS: {
    CALORIES: 'calories',
    // Macronutriments
    ACIDES_GRAS_SATURES: 'acidesGrasSatures',
    ACIDES_GRAS_MONOINSATURES: 'acidesGrasMonoinsatures',
    ACIDES_GRAS_POLYINSATURES: 'acidesGrasPolyinsatures',
    GLUCIDES: 'glucides',
    LACTOSE: 'lactose',
    LIPIDES: 'lipides',
    OMEGA3: 'omega3',
    OMEGA6: 'omega6',
    PROTEINES: 'proteines',
    SUCRES: 'sucres',
    SUCRES_HORS_LACTOSE: 'sucresHorsLactose',
    // Vitamines
    VITAMINE_A: 'vitamineA',
    VITAMINE_B1: 'vitamineB1',
    VITAMINE_B2: 'vitamineB2',
    VITAMINE_PP: 'vitaminePP',
    VITAMINE_B5: 'vitamineB5',
    VITAMINE_B6: 'vitamineB6',
    VITAMINE_B8: 'vitamineB8',
    VITAMINE_B9: 'vitamineB9',
    VITAMINE_B12: 'vitamineB12',
    VITAMINE_C: 'vitamineC',
    VITAMINE_D: 'vitamineD',
    VITAMINE_E: 'vitamineE',
    // Minéraux
    CALCIUM: 'calcium',
    PHOSPHORE: 'phosphore',
    MAGNESIUM: 'magnesium',
    // Oligoéléments
    CUIVRE: 'cuivre',
    FER: 'fer',
    MANGANESE: 'manganèse',
    ZINC: 'zinc',
  },

  FORMATED_NUTRIMENTS: {
    FORMATED_CALORIES: 'formatedCalories',
    // Macronutriments
    FORMATED_ACIDES_GRAS_SATURES: 'formatedAcidesGrasSatures',
    FORMATED_ACIDES_GRAS_MONOINSATURES: 'formatedAcidesGrasMonoinsatures',
    FORMATED_ACIDES_GRAS_POLYINSATURES: 'formatedAcidesGrasPolyinsatures',
    FORMATED_GLUCIDES: 'formatedGlucides',
    FORMATED_LIPIDES: 'formatedLipides',
    FORMATED_OMEGA3: 'formatedOmega3',
    FORMATED_OMEGA6: 'formatedOmega6',
    FORMATED_PROTEINES: 'formatedProteines',
    FORMATED_SUCRES: 'formatedSucres',
    FORMATED_SUCRES_HORS_LACTOSE: 'formatedSucresHorsLactose',
    // Vitamines
    FORMATED_VITAMINE_A: 'formatedVitamineA',
    FORMATED_VITAMINE_B1: 'formatedVitamineB1',
    FORMATED_VITAMINE_B2: 'formatedVitamineB2',
    FORMATED_VITAMINE_PP: 'formatedVitaminePP',
    FORMATED_VITAMINE_B5: 'formatedVitamineB5',
    FORMATED_VITAMINE_B6: 'formatedVitamineB6',
    FORMATED_VITAMINE_B8: 'formatedVitamineB8',
    FORMATED_VITAMINE_B9: 'formatedVitamineB9',
    FORMATED_VITAMINE_B12: 'formatedVitamineB12',
    FORMATED_VITAMINE_C: 'formatedVitamineC',
    FORMATED_VITAMINE_D: 'formatedVitamineD',
    FORMATED_VITAMINE_E: 'formatedVitamineE',
    // Minéraux
    FORMATED_CALCIUM: 'formatedCalcium',
    FORMATED_PHOSPHORE: 'formatedPhosphore',
    FORMATED_MAGNESIUM: 'formatedMagnesium',
    // Oligoéléments
    FORMATED_CUIVRE: 'formatedCuivre',
    FORMATED_FER: 'formatedFer',
    FORMATED_MANGANESE: 'formatedManganese',
    FORMATED_ZINC: 'formatedZinc',
  },

  // Autres constantes
  AGE: 'age',
  AGE_MOIS: 'ageMois',
  AJR_CALORIES: 'ajrCalories',
  CATEGORIE_ACTIVITE: 'categorieActivite',
  DATE_NAISSANCE: 'dateNaissance',
  DEPENSE_TOTALE: 'depenseTotale',
  ELEVE: 'élevé',
  EXTREMEMENT_ELEVE: 'extrêmement élevé',
  FAIBLE: 'faible',
  FEMME: 'F',
  FOOD_ITEMS: 'foodItems',
  HOMME: 'H',
  IMC: 'imc',
  IMC_MEDIAN: 'imcMedian',
  INTERPRETATION_IMC: 'interpretationImc',
  MAX: 'max',
  MAX_PROTEINES: 'maxProteines',
  METABOLISME_BASE: 'metabolismeBase',
  METABOLISME_BASE_HORAIRE: 'metabolismeBaseHoraire',
  MIN: 'min',
  MIN_PROTEINES: 'minProteines',
  NIVEAU_ACTIVITE: 'niveauActivite',
  NORMAL: 'normal',
  NUTRICALC_DATA: 'nutriCalcData',
  OPTION_LIPIDES: 'optionLipides',
  OPTION_PROTEINES: 'optionProteines',
  POIDS: 'poids',
  POIDS_CIBLE: 'poidsCible',
  PROFIL: 'profil',
  PROPORTION_GLUCIDES: 'proportionGlucides',
  PROPORTION_LIPIDES: 'proportionLipides',
  PROPORTION_PROTEINES: 'proportionProteines',
  PROTEINES_CIBLE: 'proteinesCible',
  SEXE: 'sexe',
  SOUHAIT_PERTE_POIDS: 'souhaitPertePoids',
  SURFACE_CORPORELLE: 'surfaceCorporelle',
  TAILLE: 'taille',
  TRES_ELEVE: 'très élevé',
  TRES_FAIBLE: 'très faible',
  GRAMMES: 'grammes',
  MILLILITRES: 'millilitres',
  EXCEPTIONS_FOR_PLURAL_OF_WORDS_ENDING_IN_EU: ['bleu', 'emeu', 'pneu'],
  EXCEPTIONS_FOR_PLURAL_OF_WORDS_ENDING_IN_OU: [
    'bijou',
    'caillou',
    'chou',
    'genou',
    'hibou',
    'joujou',
    'pou',
  ],
  EXCEPTIONS_FOR_PLURAL_OF_WORDS_ENDING_IN_AU: ['landau', 'sarrau'],
  EXCEPTIONS_FOR_PLURAL_OF_WORDS_ENDING_IN_AL: [
    'aval',
    'bal',
    'cal',
    'carnaval',
    'ceremonial',
    'caracal',
    'chacal',
    'choral',
    'corral',
    'etal',
    'festival',
    'recital',
    'regal',
    'val',
  ],
  EXCEPTIONS_FOR_PLURAL_OF_WORDS_ENDING_IN_AIL: [
    'aspirail',
    'bail',
    'corail',
    'email',
    'fermail',
    'soupirail',
    'travail',
    'vantail',
    'vitrail',
  ],
  UNITES: ['µg', 'cg', 'dg', 'mg', 'g', 'dg', 'hg', 'kg', 'cL', 'dL', 'mL'],
  WORD_ENDINGS: ['ail', 'al', 'au', 'eau', 'eu', 'ou', 's', 'x', 'z'],
};
